---

- name: enable forwarding (IPv4)
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward=1'
  notify:
    - reload sysctl.conf

- name: enable forwarding (IPv6)
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv6.conf.all.forwarding=1'
  notify:
    - reload sysctl.conf
